# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c172e1668f8dc1b2cccd754bb5ee197557fb4561be042b415f4f885a61ae4847248c6417feb3abbf27af1f26fa2770d38d098c3cbc733d27748816a9a72d4658

test:
  secret_key_base: badc07b3355251abe2dc50a23a85ad801ce11c720d8b7b866e1e1de4a9afac364d5a8c9105654cf4e37313be70ab4e870a87692cafe5be3381f1605f2ae96797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
